from . import hostel
from . import base_archive
from . import hostel_room
from . import hostel_student
from . import hostel_amenities
from . import hostel_category
from . import hostel_book
from . import hostel_room_category
from . import hostel_room_members
from . import assign_room_student_wizard
from . import hostel_room_availability
from . import res_config_settings